name: Deploy (self-hosted)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, production]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy
        run: |
          bash /home/ivan/djangoServer/deploy.sh

